README.md
now.json

Migrate coding-blog back to personal projects

---

content/notes/github/branch-protection-rules.md

Add note about branch protection rules

---

sandbox.config.json

Add sandbox.config.js

---

content/notes/devtools/installing-node.md

Add note about nvm vs npm package

---

content/notes/devtools/brew-and-mas.md

Add note on brew and mas

---

README.md
content/notes/codesandbox/tricks-and-pitfalls.md

Add "Open in CodeSandbox" badge

---

package.json
yarn.lock

Turn off Gatsby telemetry

---

content/notes/codesandbox/sandbox-config.md

Add note on sandbox config

---

package.json

Rename start script to develop

---

sandbox.config.json

Remove sandbox.config.json

---

content/notes/github/renovate-bot.md

Add note on Renovate Bot

---

content/notes/github/actions.md

Add note on GitHub Actions

---

content/notes/digital-garden/concept.md
content/notes/digital-garden/content-types.md

Add note on digital garden

---

.eslintrc
_drafts/bower_primer.md
_drafts/node_debugging.md
_drafts/nodenv_primer.md
_drafts/nvm_and_npm_primer.md
content/blog/2014-01-01-dummy-post-01.md
content/blog/2014-02-02-dummy-post-02.md
content/blog/2014-03-03-dummy-post-03.md
content/blog/2014-04-04-dummy-post-04.md
content/blog/2014-05-05-dummy-post-05.md
content/blog/2014-06-06-dummy-post-06.md
content/blog/2014-07-07-dummy-post-07.md
content/blog/2014-08-08-dummy-post-08.md
content/blog/2014-09-09-dummy-post-09.md
content/blog/2014-10-10-dummy-post-10.md
gatsby-config.js
package.json
yarn.lock

Add ESLint an Prettier

---

.github/workflows/code-qa.yml

Add lint check for pull requests

---

package.json
yarn.lock

Add purge script

---

package.json
yarn.lock

Add serve script

---

lint-staged.config.js
package.json
yarn.lock

Add lint-staged

---

renovate.json

Switch Renovate Bot to weekly updates

---

content/notes/next/examples.md

Add note about next.js examples

---

content/notes/design-systems/articles.md
content/notes/design-systems/color.md
content/notes/design-systems/examples.md
content/notes/design-systems/icons.md
content/notes/design-systems/people.md
content/notes/design-systems/styled-system.md
content/notes/design-systems/tailwind.md
content/notes/design-systems/theme-ui.md

Migrate 454de6e/awesome-design-systems

---

content/notes/speaking/cfp.md
content/notes/speaking/mdx-deck.md

Add note on mdx-deck

---

content/notes/dev/bundlers.md

Add note on bundlers

---

content/notes/dev/bundlers.md
content/notes/dev/packages.md

Add note about packages

---

.github/workflows/test.yml

Use yarn install --frozen-lockfile in test.yml

---

.eslintrc
package.json
yarn.lock

Use @maiertech/eslint-config for linting

---

lint-staged.config.js

Remove `git add` from lint-staged.config.js

---

.prettierrc
lint-staged.config.js
package.json
yarn.lock

Fix lint and format scripts, husky and lint-staged

---

.prettierrc
package.json
yarn.lock

Use @maiertech/prettier-config

---

.gitignore
package.json
yarn.lock

Replace cross-env with dotenv

---

content/notes/dev/curriculum.md

Migrate awesome-coding career

---

now.json

Remove now.json

---

.github/dependabot.yml

Switch Dependabot upgrades to monthly

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.vscode/settings.json

Add Codespaces config

---

.devcontainer/devcontainer.json

Set GATSBY_TELEMETRY_DISABLED in containerEnv

---

content/notes/css/layouts.md
content/notes/theme-ui/styles.md
gatsby-config.js
package.json
src/components/layout.js
src/gatsby-plugin-theme-ui/index.js
src/gatsby-theme-blog/components/layout.js
src/gatsby-theme-notes/components/layout.js
src/pages/index.js
yarn.lock

Customize layout

---

README.md
gatsby-config.js

Remove link to Codesandbox in README

---

src/components/layout.js
src/gatsby-theme-blog-core/components/post.js
src/gatsby-theme-blog-core/components/posts.js

Shadow theme-blog page templates

---

package.json
yarn.lock

Upgrade @maiertech/eslint-config

---

yarn.lock

Fix inconsistent styling of code and inlineCode

---

content/notes/css/flexbox.mdx
content/notes/css/grid.mdx
content/notes/css/layouts.mdx
content/notes/design-systems/tailwindcss.mdx
content/notes/design-systems/theme-ui/prop-forwarding.mdx
content/notes/design-systems/theme-ui/variants.mdx
content/notes/dev/eslint-and-prettier.mdx
content/notes/digital-garden/screenflow.mdx
content/notes/gatsby/gatsby-plugin-mdx.mdx
content/notes/gatsby/tagging.mdx
content/notes/github/cli.mdx
content/notes/github/git.mdx
content/notes/github/renovate-bot.mdx
content/notes/javascript/node/using-node.mdx
content/notes/javascript/react/hooks.mdx
content/notes/javascript/react/refs.mdx
content/notes/layouts/scrollytelling.mdx
content/notes/mdx/how-mdx-works.mdx
content/notes/mdx/processing.mdx
package.json
yarn.lock

Add syntax highlighting

---

content/pages/about.mdx
gatsby-config.js
package.json
yarn.lock

Upgrade @maiertech/gatsby-theme-digital-garden to v0.4.0

---

package.json
src/html.js

Add analytics

---

src/html.js

Update analytics settings

---

content/posts/github-codespaces/index.mdx

Override slug for launch post

---

package.json
yarn.lock

Exclude notes from sitemap

---

package.json
yarn.lock

Update @maiertech/gatsby-theme-digital-garden to v0.6.0

---

content/chunks/lint-staged-config/index.mdx
gatsby-config.js

Write chunk about lint-staged.config.js

---

content/posts/github-codespaces/index.mdx
gatsby-config.js
package.json
src/html.js

Change URL to coding.maier.tech

---

content/chunks/vscode-docker/index.mdx
content/chunks/vscode-remote-containers/index.mdx

Write chunks about ms-azuretools.vscode-docker and ms-vscode-remote.remote-containers

---

_flashcards/Linux/Crouton.md
package.json
yarn.lock

Regenerate yarn.lock

---

content/pages/about.mdx
content/posts/github-codespaces/index.mdx
gatsby-config.js
package.json
yarn.lock

Add post footer

---

content/posts/yarn-conflicting-package-versions/index.mdx

Final edit

---

package.json

Remove resolutions from package.json

---

content/chunks/husky-v5-pitfalls/index.mdx
content/notes/dev.to/cross-posting.mdx
content/notes/digital-garden/devto.mdx

Final edit: husky-v5-pitfalls

---

package.json
yarn.lock

Upgrade Gatsby to v3

---

gatsby-config.js
package.json
yarn.lock

Add seoTitle

---

package.json
yarn.lock

Suppress page footer for notes

---

content/posts/github-codespaces/index.mdx
package.json
yarn.lock

Fix how slugify slugifies CamelCase words

---

content/chunks/css/attribute-selectors/matching-attribute-presence/index.mdx
content/chunks/css/attribute-selectors/matching-attribute-values/index.mdx
content/chunks/css/attribute-selectors/matching-data-attributes/index.mdx

Add CSS attribute selectors thread

---

content/posts/github-codespaces/introduction/index.mdx
content/posts/github-codespaces/what-to-do-when-codespaces-is-down/index.mdx

Post: What to do when GitHub Codespaces is down?

---

content/chunks/console/rimraf/index.mdx
package.json
yarn.lock

Add rimraf command chunk

---

content/chunks/console/less/index.mdx

Add less command chunk

---

content/chunks/console/echo-command/index.mdx
package.json
yarn.lock

Add echo command chunk
